### PR TITLE
browser: cleanup

### PR DESCRIPTION
**Pull request by dcousens**
In line with what `createHmac` looks like.
Lets ensure https://github.com/crypto-browserify/createHmac/issues/3 doesn't happen here however.

Better tests are needed to ensure this.

### CODE REVIEW

**Comment by dcousens** [comment]
@calvinmetcalf will wait on your ACK for this

**Comment by calvinmetcalf** [comment]
can you rebase this on top of #2?

**Comment by dcousens** [comment]
Haha, rebased, much smaller PR.

**Comment by calvinmetcalf** [comment]
:+1:

**Pull request merged**
